const collectionDefaults=Array.isArray(window.VIDA_COLLECTION_DEFAULTS)?window.VIDA_COLLECTION_DEFAULTS:[];
const collectionPublishKey='vida_published_collection_v1';
const sitePublishKey='vida_published_site_v1';
const inquiryKey='vida_inquiries';
const readJson=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const esc=(value='')=>String(value).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function collectionPayload(){return readJson(collectionPublishKey)}
function activePieces(){const published=collectionPayload()?.pieces;return Array.isArray(published)&&published.length?published:collectionDefaults}
function visiblePieces(){return activePieces().filter(p=>p.status!=='Hidden')}
function pieceNumber(id=''){const n=String(id).match(/\d+/)?.[0]||'';return n.padStart(3,'0')}
function productUrl(piece){return `product.html?id=${encodeURIComponent(piece.id)}`}
function visualMarkup(piece){const number=pieceNumber(piece.id);if(piece.image){return `<a class="piece-visual" href="${productUrl(piece)}"><span class="visual-number">${esc(number)}</span><img src="${esc(piece.image)}" alt="${esc(piece.name)}"></a>`}if(piece.id==='VIDA 002'){return `<a class="piece-visual visual-bolt" href="${productUrl(piece)}"><span class="visual-number">${esc(number)}</span><div class="star-outline">☆</div><div class="bolt-outline">ϟ</div></a>`}return `<a class="piece-visual vida-placeholder" href="${productUrl(piece)}"><span class="visual-number">${esc(number)}</span><div class="placeholder-copy"><span>VIDA DESIGN STUDY</span><strong>${esc(piece.name)}</strong><small>Imagery in development</small></div></a>`}
function renderCollection(){const grid=document.querySelector('.collection-grid');if(!grid)return;const pieces=visiblePieces();grid.innerHTML=pieces.map((p,index)=>`<article class="piece ${index===0?'piece-hero':''}" data-piece-id="${esc(p.id)}">${visualMarkup(p)}<div class="piece-copy"><div class="piece-top"><p class="eyebrow">${esc(p.id)} • ${esc(String(p.status||'').toUpperCase())}</p><span class="price-tag">${esc(p.price||'Private')}</span></div><h3>${esc(p.name)}</h3><p class="meta">${esc(p.materials||'Fine jewelry')}</p><p class="piece-story">${esc(p.story||'')}</p><a class="piece-link" href="${productUrl(p)}">Discover the piece →</a></div></article>`).join('');}
function renderInterestOptions(){const select=document.getElementById('interestSelect');if(!select)return;const requested=new URLSearchParams(window.location.search).get('interest');const options=visiblePieces().map(p=>p.name).concat(['A custom piece','Private appointment']);select.innerHTML=options.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(requested&&options.includes(requested))select.value=requested;}
function bindInquiryForm(){const form=document.getElementById('inquiryForm');const note=document.getElementById('formNote');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const saved=readJson(inquiryKey)||[];saved.unshift({...data,createdAt:new Date().toISOString(),status:'New'});localStorage.setItem(inquiryKey,JSON.stringify(saved));form.reset();if(note)note.textContent='Inquiry saved in this preview. Direct delivery will be connected before launch.';});}
function applyLegacyProductPreview(){const main=document.querySelector('.product[data-piece-id]');if(!main)return;const p=activePieces().find(x=>x.id===main.dataset.pieceId);if(!p)return;const title=main.querySelector('.product-copy h1');const price=main.querySelector('.product-copy .price');const eyebrow=main.querySelector('.product-copy .eyebrow');const lead=main.querySelector('.product-copy>p:not(.eyebrow):not(.price)');const img=main.querySelector('.product-visual img');if(title)title.textContent=p.name;if(price)price.textContent=p.price;if(eyebrow)eyebrow.textContent=`${p.id} • ${String(p.status||'').toUpperCase()}`;if(lead)lead.textContent=p.story;if(img&&p.image){img.src=p.image;img.alt=p.name;}document.title=`${p.name} | Vida Collection by Alé`;}
function renderCreatorBar(){document.querySelector('.creator-preview-bar.unified-preview')?.remove();const collection=collectionPayload();const site=readJson(sitePublishKey);if(!collection&&!site)return;const bar=document.createElement('div');bar.className='creator-preview-bar unified-preview';const times=[];if(collection?.publishedAt)times.push(`collection ${new Date(collection.publishedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`);if(site?.publishedAt)times.push(`site ${new Date(site.publishedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`);bar.innerHTML=`<span><strong>Creator Preview Active</strong>${times.length?` • ${times.join(' • ')}`:''}</span><div class="creator-preview-actions"><a href="creator.html">Creator Studio</a><button type="button">Clear preview</button></div>`;bar.querySelector('button').onclick=()=>{localStorage.removeItem(collectionPublishKey);localStorage.removeItem(sitePublishKey);location.reload();};document.body.prepend(bar);document.body.classList.add('has-creator-preview');}
function init(){renderCollection();renderInterestOptions();bindInquiryForm();applyLegacyProductPreview();renderCreatorBar();}
document.addEventListener('DOMContentLoaded',init);
window.addEventListener('storage',e=>{if(e.key===collectionPublishKey||e.key===sitePublishKey)location.reload();});