window.VIDA_COLLECTION_DEFAULTS = [
  {id:'VIDA 001',name:'Flor de Vida',status:'One of One',visibility:'public',price:'$5,000',materials:'14K yellow gold • opal',story:'The opening one-of-one cocktail ring and anchor of the Vida collection.',image:''},
  {id:'VIDA 002',name:'Star / Bolt',status:'In Development',visibility:'public',price:'Private',materials:'10K or 14K yellow gold • openwork drop earring',story:'An open star at the ear with an elongated hollow lightning-bolt drop, designed as a recognizable Vida signature.',image:''},
  {id:'VIDA 003',name:'Luz de Alé',status:'Designer Review',visibility:'public',price:'Private',materials:'14K yellow gold • white opal • multicolor accents',story:'A luminous opal surrounded by an asymmetrical floral burst of color and flowing goldwork.',image:'assets/floral-opal-ring.svg'},
  {id:'VIDA 004',name:'Órbita',status:'Designer Review',visibility:'public',price:'Private',materials:'14K yellow gold • black opal • colored gemstone accents',story:'A celestial black opal composition framed by orbital arcs, gemstone points, moon and star details.',image:'assets/orbit-opal-ring.svg'},
  {id:'VIDA 005',name:'Entrelazado',status:'Coming Soon',visibility:'public',price:'Coming Soon',materials:'14K yellow gold • two-strand interwoven band • open negative space',story:'A continuous two-strand interwoven band with rounded polished strands, visible openings, and a sculptural profile.',image:'assets/braided-gold-band.svg'},
  {id:'VIDA 006',name:'Lazo de Luz',status:'Designer Review',visibility:'hidden',price:'Private',materials:'14K yellow gold • gemstone center',story:'A light sculptural ring direction built around a graceful looping gold form.',image:''},
  {id:'VIDA 007',name:'Lazo Eterno',status:'Designer Review',visibility:'hidden',price:'Private',materials:'14K yellow gold',story:'A more architectural interpretation of the interwoven Vida language for a statement ring.',image:''},
  {id:'VIDA 008',name:'Fuego Unido',status:'Designer Review',visibility:'hidden',price:'Private',materials:'14K yellow gold • warm-toned gemstones',story:'A bold color-led statement piece exploring heat, movement, and paired forms.',image:''}
];
